import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { theme, styled } from "../stitches.config";
export default function Home() {
  const H1 = styled("h1", {
    font: "cherry",
    color: theme.colors.secondary,
    fontSize: 48,
    width: 250,
    marginTop: 0,
    textAlign: "center",
  });

  const LetterHolder = styled("div", {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "center"
  })
  const LetterButton = styled("button", {
    height: 80,
    width: 60,
    backgroundColor: theme.colors.primary,
    border: "1px solid $secondary",
    fontSize: 32,
    display: "flex",

    alignItems: "center",
    justifyContent: "center",
    borderRadius: 4,
    color: 'white',
    boxShadow: `0px 2px 0px ${theme.colors.secondary}`,
  })
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/img/eggs.svg" />
        <H1 className="cherry">Scrambled Letters</H1>
        <LetterHolder>
          <LetterButton className="cherry">L</LetterButton>
          <LetterButton className="cherry">M</LetterButton>
          <LetterButton className="cherry">O</LetterButton>
          <LetterButton className="cherry">P</LetterButton>
          <LetterButton className="cherry">A</LetterButton>
          <LetterButton className="cherry">R</LetterButton>
          <LetterButton className="cherry">T</LetterButton>
          <LetterButton className="cherry">K</LetterButton>
        </LetterHolder>
      </main>
    </>
  );
}
